install: composer install

language: php

php:
  - 5.5
  - 5.6

script:
  - vendor/bin/phpcs --standard=PSR1,PSR2 Soneritics/Framework/
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml test/

after_script:
  - php vendor/bin/coveralls -v
