CREATE TABLE `logs` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`level` VARCHAR(50) NOT NULL,
	`message` TEXT NOT NULL,
	`context` LONGTEXT NOT NULL,
	`datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
);